### ISSUE TITLE
ENOTFOUND

### ISSUE THREAD

**Issue by brimob-sowax** [downygg/ManaClaimer#6]
![Screenshot 2024-06-06 194502](https://github.com/downygg/ManaClaimer/assets/114806654/94a7c89c-689d-4812-8bc4-a389089200c5)
  
eror nih om

**Comment by downygg** [comment]
coba lagi aja, kemunginan error di rpc nya

**Comment by brimob-sowax** [comment]
> coba lagi aja, kemunginan error di rpc nya

masih sama om, blm bisa

**Comment by brimob-sowax** [comment]
![Screenshot 2024-06-10 152312](https://github.com/downygg/ManaClaimer/assets/114806654/389e9b3d-acd6-4491-8a64-0bf1774a1719)

keterangan erornya berubah

**Comment by downygg** [comment]
git pull ulang, udah di update

**Comment by brimob-sowax** [comment]
makasih om
